---
- name: Ansible Playbook
  hosts: Development
  become: true
  user: ubuntu
  gather_facts : true
  roles:
    - apache
    - php
    - mysql
    
  vars:
    ansible_aws_ssm_region: us-east-1
    ansible_connection: community.aws.aws_ssm
    ansible_aws_ssm_bucket_name: '{{ krishna-tf-bucket }}'